# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 个人博客首页
email: kongyangming@yeah.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright © Pwnny's Blog<br/>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
github_username:  ooooYoi

# Build settings
markdown: kramdown
theme: minima
